# 配置端口
server:
        port: 8789
spring:
# 配置数据源
        datasource:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
                username: root
                password: 12345678
                type: com.alibaba.druid.pool.DruidDataSource
        security:
          user:
            name: bobo
            password: xyz

# mybatis 相关 configurations
mybatis-plus:
# xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
        mapper-locations: classpath:mapper/*.xml
# 以下配置均有默认值,可以不设置
        global-config:
         db-config:
# 主键类型,大小写不敏感 AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"
                id-type: auto
# 字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
                field-strategy: not_empty
#数据库类型, 大小写不敏感
                db-type: mysql
                configuration:
# 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
                map-underscore-to-camel-case: true
# 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
                call-setters-on-nulls: true
# 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
                log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
